export default {
  guide: {
    "Body Armors": "Body",
    "Boots": "Boots",
    "Flasks": "Flask",
    "Gloves": "Gloves",
    "Helmets": "Helmet",
    "Jewellery": "Amulet",
    "Jewels": "Jewel",
    "Offhands": "Shield",
    "One Handed Weapons": "OneHand",
    "Two Handed Weapons": "TwoHand",

    "Cobalt Jewel": "JewelInt",
    "Crimson Jewel": "JewelStr",
    "Ghastly Eye Jewel": "JewelAbyssSummoner",
    "Hypnotic Eye Jewel": "JewelAbyssCaster",
    "Murderous Eye Jewel": "JewelAbyssMelee",
    "Prismatic Jewel": "JewelPrismatic",
    "Searching Eye Jewel": "JewelAbyssRanged",
    "Timeless Jewel": "JewelTimeless",
    "Viridian Jewel": "JewelDex",

    "Hybrid Flask": "FlaskHybrid",
    "Iron Flask": "FlaskIron",
    "Life Flask": "FlaskLife",
    "Mana Flask": "FlaskMana",
    "Utility Flask": "FlaskUtility",

    "Amulet": "Amulet",
    "Belt": "Belt",
    "Ring": "Ring",
    "Unset Ring": "UnsetRing",

    "Body Armor (DEX)": "BodyDex",
    "Body Armor (INT)": "BodyInt",
    "Body Armor (STR)": "BodyStr",
    "Body Armor (DEX/INT)": "BodyDexInt",
    "Body Armor (STR/DEX)": "BodyStrDex",
    "Body Armor (STR/INT)": "BodyStrInt",
    "Body Armor (STR/DEX/INT)": "BodyStrDexInt",

    "Boots (DEX)": "BootsDex",
    "Boots (INT)": "BootsInt",
    "Boots (STR)": "BootsStr",
    "Boots (DEX/INT)": "BootsDexInt",
    "Boots (STR/DEX)": "BootsStrDex",
    "Boots (STR/INT)": "BootsStrInt",
    "Boots (Ward)": "BootsExpedition",

    "Gloves (DEX)": "GlovesDex",
    "Gloves (INT)": "GlovesInt",
    "Gloves (STR)": "GlovesStr",
    "Gloves (DEX/INT)": "GlovesDexInt",
    "Gloves (STR/DEX)": "GlovesStrDex",
    "Gloves (STR/INT)": "GlovesStrInt",
    "Gloves (Ward)": "GlovesExpedition",

    "Helmets (DEX)": "HelmetDex",
    "Helmets (INT)": "HelmetInt",
    "Helmets (STR)": "HelmetStr",
    "Helmets (DEX/INT)": "HelmetDexInt",
    "Helmets (STR/DEX)": "HelmetStrDex",
    "Helmets (STR/INT)": "HelmetStrInt",
    "Helmets (Ward)": "HelmetExpedition",

    "Quiver": "Quiver",
    "Shield (DEX)": "ShieldDex",
    "Shield (INT)": "ShieldInt",
    "Shield (STR)": "ShieldStr",
    "Shield (DEX/INT)": "ShieldDexInt",
    "Shield (STR/DEX)": "ShieldStrDex",
    "Shield (STR/INT)": "ShieldStrInt",
    "Shield (Ward)": "ShieldExpedition",

    "Claw": "Claw",
    "Dagger": "Dagger",
    "One Hand Axe": "OneHandAxe",
    "One Hand Mace": "OneHandMace",
    "One Hand Sword": "OneHandSword",
    "Rune Dagger": "RuneDagger",
    "Sceptre": "Sceptre",
    "Rapier": "Rapier",
    "Wand": "Wand",

    "Bow": "Bow",
    "Staff": "Staff",
    "Two Hand Axe": "TwoHandAxe",
    "Two Hand Mace": "TwoHandMace",
    "Two Hand Sword": "TwoHandSword",
    "Warstaff": "Warstaff",
  },
};
